django/allgo/api/v1/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'

urlpatterns = [
    url(r'^jobs$', views.jobs, name='jobs'),
    url(r'^metrics/(?P<what>\w+)/(?P<app_id>\d+)', views.Metrics.as_view(), name='metrics'),
    url(r'^jobs/(?P<pk>\d+)$', views.APIJobView.as_view(), name='job'),
    url(r'^jobs/(?P<pk>\d+)/abort$', views.APIJobAbortView.as_view(), name='job_abort'),
    url(r'^datastore/(?P<pk>\d+)/(.*)$', views.APIDownloadView.as_view(), name='download'),
]

django/allgo/main/urls.py
# -*- coding: utf-8 -*-
"""Main url module

This module handles all URLs related to the `main` django application.

Below a short description of the different type of URLs available for
front-end.

/apps                       list all the public apps
/apps/author/<username>     list all public apps of a particular owner
/apps/tag/<tag>             list all apps according to a particular tag
/app[s]/<docker_name>       app details

/runners/                   list all runners of a given user
/runners/create             create a runner
/runners/<runner_id>/       details of a runner
/runners/<runner_id>/update update a given runner
/runners/<runner_id>/delete delete a given runner

/profile                    profile of user (name, first name, email)
/profile/password           update password
/profile/security           SSH key and token

/jobs/                      list all jobs of the user
/jobs/<job_id>/             details of a given job
/jobs/<job_id>/delete       delete the job
/jobs/<job_id>/issue        report an issue
/jobs/<job_id>/relaunch     re-run a given job

# same url schema as the API, but here display graphs.
/metrics                    form to define the graph to display

Todo:
    - make the app details available both at /app/<docker_name> (historic
      version) and at /apps/<docker_name>/ (more coherent with the overall
      system.

See also:
    This url file depends on the main `urls.py` file located in the `config`
    folder at the root of the Django application.
"""
from functools import partial
# Third party import
from django.conf.urls import url
import django.conf.urls
import django.views.defaults

# Local import
from . import views

app_name = 'main'

urlpatterns = [
    url(r'^$', views.IndexDetail.as_view(), name="home"),
    url(r'^apps/$', views.WebappList.as_view(), name='webapp_list'),
    url(r'^apps/_authors/(?P<username>[\w.@+-]+)/$', views.UserWebappList.as_view(),
        name='user_webapp_list'),
    url(r'^apps/_create/$', views.WebappCreate.as_view(), name='webapp_creation'),
    url(r'^apps/_import/$', views.WebappImport.as_view(), name='webapp_import'),
    url(r'^apps/(?P<docker_name>[\w-]+)/import$', views.WebappVersionImport.as_view(),
        name="webapp_version_import"),
    url(r'^apps/(?P<docker_name>[\w-]+)/tokens$', views.WebappTokenCreate.as_view(),
        name="webapp_token_create"),
    url(r'^apps/(?P<docker_name>[\w-]+)/tokens/(?P<token>\w+)/delete$', views.WebappTokenDelete.as_view(),
        name="webapp_token_delete"),
    url(r'^apps/(?P<docker_name>[\w-]+)/update$', views.WebappUpdate.as_view(),
        name="webapp_update"),
    url(r'^apps/(?P<docker_name>[\w-]+)/sandbox$', views.WebappSandboxPanel.as_view(),
        name="webapp_sandbox_panel"),
    url(r'^apps/(?P<docker_name>[\w-]+)/versions/$', views.WebappVersionList.as_view(),
        name="webapp_version_list"),
    url(r'^apps/(?P<docker_name>[\w-]+)/versions/(?P<pk>\d+)/update',
        views.WebappVersionUpdate.as_view(), name="webapp_version_update"),
    url(r'^apps/(?P<docker_name>[\w-]+)/json$', views.WebappJson.as_view(), name='webapp_json'),
    url(r'^apps/(?P<docker_name>[\w-]+)$', views.JobCreate.as_view(), name='webapp_detail'),

    url(r'^tags/$', views.TagList.as_view(), name='tag_list'),
    url(r'^tags/(?P<slug>[\w-]+)$', views.TagWebappList.as_view(), name='tag_webapp_list'),

    url(r'^jobs/$', views.JobList.as_view(), name='job_list'),
    url(r'^jobs/(?P<pk>\d+)$', views.JobDetail.as_view(), name='job_detail'),
    url(r'^jobs/(?P<pk>\d+)/abort$', views.JobAbort.as_view(), name='job_abort'),
    url(r'^jobs/(?P<pk>\d+)/delete$', views.JobDelete.as_view(), name='job_delete'),
    url(r'^jobs/(?P<pk>\d+)/archive$', views.JobFileDownloadAll.as_view(), name='job_download_all'),
    url(r'^jobs/(?P<pk>\d+)/download/(?P<filename>(.*))$', views.JobFileDownload.as_view(),
        name='job_download_file'),

    url(r'^profile$', views.UserUpdate.as_view(), name='user_detail'),
    url(r'^profile/token/update$', views.UserToken.as_view(), name='user_token'),
    url(r'^profile/ssh/add$', views.UserSSHAdd.as_view(), name='user_ssh_add'),
    url(r'^profile/ssh/delete$', views.UserSSHDelete.as_view(), name='user_ssh_delete'),
    url(r'^profile/password$', views.UserPasswordUpdate.as_view(), name='user_password'),
    url(r'^profile/need_validation$', views.UserNeedValidation.as_view(),
        name='user_need_validation'),

    url(r'^metrics$', views.Metrics.as_view(), name='metrics'),

    # Terms of service urls
    url(r'^tos$', views.TosDetail.as_view(), name='tos_detail'),

    #  url(r'^runners/$', views.RunnerList.as_view(), name='runner_list'),
    #  url(r'^runners/_add$', views.RunnerCreate.as_view(), name='runner_create'),
    #  url(r'^runners/(?P<pk>\d+)/update$', views.RunnerUpdate.as_view(), name='runner_update'),
    #  url(r'^runners/(?P<pk>\d+)/delete$', views.RunnerDelete.as_view(), name='runner_delete'),

    url(r'^auth$', views.auth, name="auth"),


    # important legacy URLs (from the rails implementation)
    url(r'^webapps/(?P<pk>\d+)/?$',  views.LegacyWebappDetail.as_view()),
    url(r'^app/(?P<slug>[\w-]+)/?$', views.LegacyWebappDetail.as_view()),
]


# error handlers
# NOTE: the 404 and 500 handlers are ignored when settings.DEBUG is enabled
django.conf.urls.handler400 = partial(views.error_handler,
        400, "Bad Request", django.views.defaults.bad_request)
django.conf.urls.handler403 = partial(views.error_handler,
        403, "Forbidden", django.views.defaults.permission_denied)
django.conf.urls.handler404 = partial(views.error_handler,
        404, "Not Found", django.views.defaults.page_not_found)
django.conf.urls.handler500 = partial(views.error_handler,
        500, "Server Error", django.views.defaults.server_error)

django/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views


urlpatterns = [
    # Django admin
    url(settings.ADMIN_URL, admin.site.urls),

    # Allgo stuff here
    url(r'', include('main.urls')),
    url(r'', include('jwt_auth.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^api/v1/', include('api.v1.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        url(r'^400/$',
            default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$',
            default_views.permission_denied,
            kwargs={'exception': Exception('Permission denied!')}),
        url(r'^404/$',
            default_views.page_not_found,
            kwargs={'exception': Exception('Page not found!')}),
        url(r'^500/$', default_views.server_error),
    ]

django/allgo/main/models.py
from __future__ import unicode_literals
import datetime
import os

from django.conf import settings
from django.contrib import auth
from django.contrib.auth.models import User, AnonymousUser
from django.core.validators import MinValueValidator, RegexValidator, ValidationError
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.crypto import get_random_string
from jsonfield import JSONField
from taggit.managers import TaggableManager
from allauth.account.models import EmailAddress


from .validators import job_param_validator, docker_container_id_validator, \
                        docker_tag_validator, docker_name_validator, \
                        sshkey_validator, token_validator


def generate_token(length=32):
    """ Generate a random string according to its length.

    This function has been created to ensure that the function is called
    every time an object is created.

    Args:
        length (int): number of characters for the token. (default = 32)

    Returns:
        token as a string of n characters.

    """
    return get_random_string(length)

class BaseModel(models.Model):
    """Base model for all allgo models

    This base class overrides .save() to enforce validation of the model
    constraints before creating or updating an entry.

    The validation is automatically performed unless `force_insert` or
    `force_update` is true.

    see also:
    - https://www.xormedia.com/django-model-validation-on-save/
    - https://en.wikipedia.org/wiki/Fail-fast
    """
    def save(self, force_insert=False, force_update=False, **kw):
        if not (force_insert or force_update):
            self.full_clean()
        super().save(force_insert, force_update, **kw)

    class Meta:
        abstract = True


class TimeStampModel(BaseModel):
    """
    An abstract base class model that provides self-updating ``created_at`` and
    ``updated_at`` fields.
    """

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class AllgoUser(BaseModel):
    """
    Class linked to the Django user management. If there is a need to add a
    field related to a user, it should be added here and not in the auth_user
    table.
    """

    sshkey = models.TextField(null=True, blank=True,
            validators=[sshkey_validator])
    token = models.CharField(max_length=32, default=generate_token,
            validators=[token_validator])

    # Relationships
    user = models.OneToOneField(
            User, on_delete=models.CASCADE, related_name="allgouser")

    class Meta:
        db_table = 'dj_users'
        verbose_name = 'allgo user'
        verbose_name_plural = 'allgo users'

    def __str__(self):
        return self.user.username


class DockerOs(BaseModel):
    """
    Contains the different Operating Systems that a user can choose from to
    build its container.
    """

    # Fields
    name = models.CharField(max_length=255)
    version = models.CharField(max_length=255,
            validators=[docker_tag_validator])
    docker_name = models.CharField(max_length=255,
            validators=[docker_name_validator])

    class Meta:
        db_table = 'dj_docker_os'

    def __str__(self):
        return self.name + ' ' + self.version


class JobQueue(TimeStampModel):
    """
    Data regarding the type of queues available for the system.
    """

    # Fields
    name = models.CharField(max_length=255)
    timeout = models.IntegerField(blank=True, null=True,
            validators=[MinValueValidator(1)])
    is_default = models.BooleanField()

    class Meta:
        db_table = 'dj_job_queues'

    def __str__(self):
        return self.name



class Webapp(TimeStampModel):
    """
    Webapp model related to the creation and management of a particular web
    app belonging to one or more users.
    """

    #### Sandbox States ####
    IDLE = 0            # no active sandbox
    RUNNING = 1         # the sandbox is running
    STARTING = 2        # the sandbox is starting
    START_ERROR = 3     # the sandbox failed to start
    STOPPING = 4        # the sandbox is stopping
    STOP_ERROR = 5      # the sandbox failed to stop

    SANDBOX_STATE_CHOICES = (
        (IDLE, 'IDLE'),
        (RUNNING, 'RUNNING'),
        (STARTING, 'STARTING'),
        (START_ERROR, 'START_ERROR'),
        (STOPPING, 'STOPPING'),
        (STOP_ERROR, 'STOP_ERROR'),
    )

    # Notes about sandbox states
    #
    # - Possible state transitions
    #   - by django:
    #       (any) -> STARTING       (sandbox start order)
    #       (any) -> STOPPING       (sandbox stop order)
    #
    #   - by the controller:
    #       STARTING -> RUNNING     (successfully started)
    #       STARTING -> START_ERROR (start error)
    #       STOPPING -> IDLE        (successfully stopped)
    #       STOPPING -> STOP_ERROR  (stop error)
    #
    # - Both django and the controller are allowed to change the state, but
    #   django has the priority. Transitions by the controller must be performed
    #   *atomically* (compare and swap).
    #
    # - In the STARTING state, the docker image for creating the sandbox is
    #   specified by the 'sandbox_version_id' field (if not NULL), or by the
    #   'docker_os_id' (if sandbox_version_id is NULL).
    #
    # - In the STOPPING state, sandbox_version_id must be reset to NULL (to
    #   avoid later issues with foreign key constraints). If a new version has
    #   to be committed before destroying the sandbox, django may create a new
    #   WebappVersion entry in the SANDBOX state.
    #
    # - Errors (in states START_ERROR and STOP_ERROR) are generally
    #   recoverable. Django can switch back to STARTING/STOPPING for retrying
    #   the operation.
    #

    # Fields
    name = models.CharField(unique=True, max_length=255)
    description = models.TextField(blank=True, null=True)

    # Should given according to the number of users declared as admin to this
    # app
    contact = models.CharField(max_length=255, blank=True, null=True)

    # Logo
    logo_file_name = models.CharField(max_length=255, blank=True, null=True)
    logo_content_type = models.CharField(max_length=255, blank=True, null=True)
    logo_file_size = models.IntegerField(blank=True, null=True)
    logo_updated_at = models.DateTimeField(blank=True, null=True)

    # Default quota
    default_quota = models.IntegerField(blank=True, null=True)

    # Docker and parameters related stuff
    docker_name = models.CharField(max_length=255, unique=True, validators=[
        docker_name_validator,
        # 'root' and 'sshd' are reserved because webapp docker_names are mapped
        # to system users inside the ssh container
        # '_.*' is reserved because of url conflicts
        RegexValidator(r"\A(root\Z|sshd\Z|_)", inverse_match=True,
            message="This is a reserved name"),
        ])
    readme = models.IntegerField(blank=True, null=True)
    entrypoint = models.CharField(max_length=255, blank=True,
            validators=[RegexValidator(r"\A/[/\w+._-]*[\w+._-]\Z",
                "Malformatted path")])
    exec_time = models.IntegerField(blank=True, null=True)
    private = models.BooleanField(default=1)

    #FIXME: unused field
    access_token = models.CharField(max_length=255, blank=True, null=True,
            validators=[token_validator])
    sandbox_state = models.IntegerField(null=True, choices=SANDBOX_STATE_CHOICES, default=IDLE)
    sandbox_version = models.ForeignKey('WebappVersion', on_delete=models.CASCADE,
            null=True, blank=True, related_name='webappversions')
    notebook_gitrepo = models.CharField(max_length=255, blank=True, null=True)

    memory_limit = models.BigIntegerField(null=True,
            validators=[MinValueValidator(0)])

    allow_param_chars = models.CharField(max_length=16, blank=True)

    # flag indicating if this webbapp was imported from rails
    # (if True, then we can import webapp versions)
    imported = models.BooleanField(default=False)

    # Relationships

    # A webapp has one docker os type
    docker_os = models.ForeignKey(DockerOs, on_delete=models.CASCADE, related_name="webappdockeros")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="webappuser")
    job_queue = models.ForeignKey(JobQueue, on_delete=models.CASCADE, related_name="webappjobqueue")
    tags = TaggableManager()

    class Meta:
        db_table = 'dj_webapps'

    def __str__(self):
        return self.name

    @staticmethod
    def _resolve_user(actor):
        if actor is None or isinstance(actor, User):
            return actor
        elif isinstance(actor, AllgoUser):
            return actor.user
        elif isinstance(actor, Runner):
            allgo_user = actor.user
            return None if allgo_user is None else allgo_user.user
        elif isinstance(actor, AnonymousUser):
            return None
        raise TypeError()

    def is_pullable_by(self, actor, *, client_ip=None):
        """Return True if the given actor is allowed to pull an image of this webapp

        `actor` may be a User, AllgoUser, Runner, Token or None

        `client_ip` is client IP address (used for limiting admin/open_bar
        access to the adresses listed in ALLGO_ALLOWED_IP_ADMIN)
        """
        if (isinstance(actor, Runner) and actor.open_bar
                and is_allowed_ip_admin(client_ip)):
            return True

        if isinstance(actor, Token):
            # deploy tokens are just for pushing (for the moment)
            return False
        user = self._resolve_user(actor)
        if user == self.user:
            return True
        elif user is not None and user.is_superuser and client_ip:
            return is_allowed_ip_admin(client_ip)
        return False

    def is_pushable_by(self, actor):

django/allgo/templates/webapp_detail.html
{% extends "base.html" %}
{% load static converters htmlattrs humanize %}

{% block title %}{{ webapp.name | fancy_webapp_name | title }} application{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'main:webapp_list' %}">Applications</a></li>
<li class="breadcrumb-item active" aria-current="page">{{ webapp.name | fancy_webapp_name | title }}</li>
{% endblock %}

{% block content %}
<div class="container">
  <div class="allgo-page">
    <div class="row">


      <div class="col">
        <h1>
          {% if webapp.logo_file_name %}
          <img class="card-img-top img-thumbnail rounded-circle mx-auto" src="{% get_media_prefix %}{{ webapp.docker_name }}/{{ webapp.logo_file_name }}" alt="{{ webapp.title }} logo" style="max-width: 45px;">
          {% endif %}
          {{ webapp.name | fancy_webapp_name | title }}</h1>
      </div>
      <div class="col text-right">
          {% if webapp.user == user %}
          <a class="fa-layers fa-2x"
            href="{% url 'main:webapp_update' webapp.docker_name %}"
            data-toggle="tooltip"
            data-placement="top"
            title="Edit properties">
            <i class="fas fa-square"></i>
            <i class="fa-inverse fas fa-pencil-alt" data-fa-transform="shrink-7 down-.25 left-.25"></i>
            <span class="text-hide">Edit properties</span>
          </a>

          <a class="fa-layers fa-2x"
            href="{% url 'main:webapp_sandbox_panel' webapp.docker_name %}"
            data-toggle="tooltip"
            data-placement="top"
            title="Create new version">
            <i class="fas fa-square"></i>
            <i class="fa-inverse fas fa-plus" data-fa-transform="shrink-7 down-.25 left-.25"></i>
            <span class="text-hide">Create a new version</span>
          </a>

          {% if webapp.imported %}
          <a class="fa-layers fa-2x"
            href="{% url 'main:webapp_version_import' webapp.docker_name %}"
            data-toggle="tooltip"
            data-placement="top"
            title="Import version">
            <i class="fas fa-square"></i>
            <i class="fa-inverse fas fa-cloud-download-alt" data-fa-transform="shrink-7 down-.25 left-2"></i>
            <span class="text-hide">Import version</span>
          </a>
          {% endif %}
          {% endif %}

          <a class="fa-layers fa-2x"
            href="{% url 'main:webapp_version_list' webapp.docker_name %}"
            data-toggle="tooltip"
            data-placement="top"
            title="List versions">
            <i class="fas fa-square"></i>
            <i class="fa-inverse fas fa-tasks" data-fa-transform="shrink-7 down-.25 left-.25"></i>
            <span class="text-hide">List versions</span>
          </a>
      </div>
    </div>

      <ul class="list-inline app-tags small mb-4">
        <li class="list-inline-item">{{ webapp.contact | email2name }}</li>
        <li class="list-inline-item">Updated {{ webapp.updated_at | naturalday }}</li>
        <li class="list-inline-item"><i class="fas fa-tags"></i></li>
        {% for tag in webapp.tags.all %}
        <li class="list-inline-item"><a class="badge badge-secondary" href="{% url 'main:tag_webapp_list' tag.slug %}">{{ tag.name }}</a></li>
        {% endfor %}
      </ul>

      {% if readme %}
        {{ readme | markdown | safe }}
      {% elif webapp.description %}
        {{ webapp.description | markdown | safe }}
      {% else %}
        <p>No description available</p>
      {% endif %}

    {# Link to the sandbox panel #}
    {% if webapp.sandbox_state != webapp.IDLE and user == webapp.user %}
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">This application has an active sandbox</h5>
        <p class="card-text">You can run test jobs using the job submission form below</p>
        <p class="card-text">Once you are done, you can <b>commit</b> a new version
        (to save your work permanently and make it usable by other users)
        or <b>rollback</b> (to discard your changes)</p>
        <a href="{% url 'main:webapp_sandbox_panel' webapp.docker_name %}" class="card-link">Go to the sandbox panel</a>
      </div>
    </div>
    {% endif %}

    {% if versions %}
    {# Panels #}
    <ul class="nav nav-tabs mt-3">
      <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#create-job"><i class="fas fa-database"></i> Run a job</a></li>
      <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#api"><i class="fas fa-terminal"></i> Use the API</a></li>
      {% if webapp.notebook_gitrepo %}
      <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#notebook"><i class="fas fa-file-alt"></i> Notebook</a></li>
      {% endif %}
    </ul>

      <div class="tab-content">
        <div class="tab-pane active" id="create-job">
          {% if user.is_authenticated %}
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-group" id="files-form-group">
              {{ form.files.label_tag }}
              {% for i in file_input_ids %}
              <div class="input-group"{% if not forloop.first %} hidden{% endif %}>
		<div class="input-group-prepend">
                  <button type="button" class="btn btn-outline-secondary" data-action="remove">×</button>
		</div>
                <div class="custom-file">
                  <input id="input-file-{{i}}" class="custom-file-input" type="file" name="{{ form.files.name }}" multiple>
                  <label for="input-file-{{i}}" class="custom-file-label"></label>
                </div>
              </div>
              {% endfor %}
              <small class="form-text text-muted">{{ form.files.help_text }}</small>
            </div>

            <div class="form-group">
              {{ form.param | label_with_classes:"d-block" }}
              <div class="input-group">
                <div class="input-group-prepend">
                  <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Presets</button>
                  <div class="dropdown-menu">
                    {% for choice in form.webapp_parameters.field.queryset %}
                      <a class="dropdown-item" href="#" data-param="{{ choice.value }}">{{ choice.name }}</a>
                    {% empty %}
                    <p class="dropdown-item">No presets available</p>
                    {% endfor %}
                  </div>
                </div>
                {{ form.param | attr:"placeholder:Type your parameters here" | add_class:"form-control dropdown-value" }}
              </div>
              <small class="form-text text-muted">{{ form.param.help_text }}</small>
            </div>

            <div class="row">
              <div class="col form-group">
                {{ form.version.label_tag }}
                <select name="version" id="id_version" class="form-control">
                  {% for choice in versions %}
                  <option value="{{ choice }}">{{ choice }}</option>
                  {% endfor %}
                </select>
                <small class="form-text text-muted">{{ form.version.help_text }}</small>
              </div>

              <div class="col form-group">
                {{ form.queue_id.label_tag }}

                <select name="{{ form.queue_id.name }}" id="{{ form.queue_id.id_for_label }}" class="form-control">
                  {% for choice in form.queue_id.field.queryset %}
                  <option value="{{ choice.pk }}"
                    {% if choice.pk == webapp.job_queue_id %} selected {% endif %}
                    >{{ choice | fancy_job_queue }}</option>
                  {% endfor %}
                </select>
                <small class="form-text text-muted">{{ form.queue_id.help_text }}</small>
              </div>
            </div>

            <input class="btn btn-primary" type="submit" value="Run this job">
        </form>


        {% else %}
          <p class="mt-3">In order to run a job you need to be <a href="{{ sign_in_url }}" title="Sign in on A||Go">identified</a>
          or <a href="{% url 'account_signup' %}" title="Sign up on A||Go">register a new account</a>.</p>
        {% endif %}
        </div>

        <div class="tab-pane" id="api">
          <p class="mt-3"><a href="https://allgo.gitlabpages.inria.fr/doc/api.html">API Reference</a></p>

          {% for description, command in api_cmds %}
          <p class="mt-3 mb-0">{{ description }}</p>
          <div class="row">
            <div class="col-11">
              <pre><code class="lang-bash">{{ command | command_multiline }}</code></pre>
            </div>
            <div class="col-1">
              <button 
                 class="btn btn-primary js-copy mt-2"
                 data-toggle="tooltip"
                 data-copy="{{ command | command_oneline }}"
                 data-placement="top"
                 title="Copy to clipboard" type="button"><i class="fas fa-clipboard"></i><span class="text-hide">Copy to clipboard</span></button>
            </div>
          </div>
          {% endfor %}
        </div>

        {% if webapp.notebook_gitrepo %}
        <div class="tab-pane" id="notebook">
          <p class="mt-3">A Jupyter notebook is available to try the application online. You can
          launch it <a href="/jupyter?repo={{ webapp.notebook_gitrepo }}" title="Jupyter notebook">using this link</a>.</p>
          <p class="small text-muted">If you don't know what Jupyter is, you can <a href="https://jupyter.org/" title="Project Jupyter">visit their website</a>.</p>
        </div>
        {% endif %}
      </div>

    {% endif %}{# app has versions #}
    </div>
  </div>
</div>
{% endblock %}

{% block messages %}
{{ block.super }}
{% for field in form %}
  {% for error in field.errors %}
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <div class="container">{{ error|escape }}</div>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% endfor %}
{% endfor %}
{% endblock %}

{% block javascript %}
{{ block.super }}
<script defer src="{% static 'js/tooltip.js' %}"></script>
<script defer src="{% static 'js/copy.js' %}"></script>
<script defer src="{% static 'js/bs-custom-file-input.min.js' %}"></script>
<script defer>
$(document).ready(function(){
    {% comment %}
        Support for multiple file selectors

        HTML allows uploading multiple files via a single file selector:
            <input type="file" multiple>

        However most browser won't allow uploading files from separate
        directories, which is bad for user experience. We need to support
        multiple selectors.

        Creating additional selectors dynamically is a possible approach, but
        it seems to break firefox (as of esr 68). The requests sent by the
        browser are empty and  django reports a CSRF token failure.

        Therefore our approach is to generate the form with a fixed set of file
        selectors and keep them hidden until they are needed.
        

     {% endcomment %}
    var groups = $("#files-form-group").find(".input-group");

    {# ensure that: #}
    {#  - all non-empty file selectors are visible   #}
    {#  - exactly one empty file selector is visible #}
    function refresh_visibility() {
        var has_empty_slot = false;
        groups.each(function(_, grp) {
            if ($(grp).find("input").val() == "") {
                if (has_empty_slot) {
                    grp.setAttribute("hidden", "");
                    return;
                }
                has_empty_slot = true;
            }
            grp.removeAttribute("hidden");
        });
    }
    
    function on_remove(ev) {
        grp = $(ev.target).parentsUntil(".input-group").last().parent();
        grp.find("input").val("");
        grp.find("label").text("");
        refresh_visibility();
    }

    bsCustomFileInput.init();
    groups.find("button[data-action='remove']").click(on_remove);
    groups.find("input").change(refresh_visibility);
    refresh_visibility();
});
</script>
{% endblock %}