django/allgo/api/v1/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'

urlpatterns = [
    url(r'^jobs$', views.jobs, name='jobs'),
    url(r'^metrics/(?P<what>\w+)/(?P<app_id>\d+)', views.Metrics.as_view(), name='metrics'),
    url(r'^jobs/(?P<pk>\d+)$', views.APIJobView.as_view(), name='job'),
    url(r'^jobs/(?P<pk>\d+)/abort$', views.APIJobAbortView.as_view(), name='job_abort'),
    url(r'^datastore/(?P<pk>\d+)/(.*)$', views.APIDownloadView.as_view(), name='download'),
]

django/allgo/main/urls.py
# -*- coding: utf-8 -*-
"""Main url module

This module handles all URLs related to the `main` django application.

Below a short description of the different type of URLs available for
front-end.

/apps                       list all the public apps
/apps/author/<username>     list all public apps of a particular owner
/apps/tag/<tag>             list all apps according to a particular tag
/app[s]/<docker_name>       app details

/runners/                   list all runners of a given user
/runners/create             create a runner
/runners/<runner_id>/       details of a runner
/runners/<runner_id>/update update a given runner
/runners/<runner_id>/delete delete a given runner

/profile                    profile of user (name, first name, email)
/profile/password           update password
/profile/security           SSH key and token

/jobs/                      list all jobs of the user
/jobs/<job_id>/             details of a given job
/jobs/<job_id>/delete       delete the job
/jobs/<job_id>/issue        report an issue
/jobs/<job_id>/relaunch     re-run a given job

# same url schema as the API, but here display graphs.
/metrics                    form to define the graph to display

Todo:
    - make the app details available both at /app/<docker_name> (historic
      version) and at /apps/<docker_name>/ (more coherent with the overall
      system.

See also:
    This url file depends on the main `urls.py` file located in the `config`
    folder at the root of the Django application.
"""
from functools import partial
# Third party import
from django.conf.urls import url
import django.conf.urls
import django.views.defaults

# Local import
from . import views

app_name = 'main'

urlpatterns = [
    url(r'^$', views.IndexDetail.as_view(), name="home"),
    url(r'^apps/$', views.WebappList.as_view(), name='webapp_list'),
    url(r'^apps/_authors/(?P<username>[\w.@+-]+)/$', views.UserWebappList.as_view(),
        name='user_webapp_list'),
    url(r'^apps/_create/$', views.WebappCreate.as_view(), name='webapp_creation'),
    url(r'^apps/_import/$', views.WebappImport.as_view(), name='webapp_import'),
    url(r'^apps/(?P<docker_name>[\w-]+)/import$', views.WebappVersionImport.as_view(),
        name="webapp_version_import"),
    url(r'^apps/(?P<docker_name>[\w-]+)/tokens$', views.WebappTokenCreate.as_view(),
        name="webapp_token_create"),
    url(r'^apps/(?P<docker_name>[\w-]+)/tokens/(?P<token>\w+)/delete$', views.WebappTokenDelete.as_view(),
        name="webapp_token_delete"),
    url(r'^apps/(?P<docker_name>[\w-]+)/update$', views.WebappUpdate.as_view(),
        name="webapp_update"),
    url(r'^apps/(?P<docker_name>[\w-]+)/sandbox$', views.WebappSandboxPanel.as_view(),
        name="webapp_sandbox_panel"),
    url(r'^apps/(?P<docker_name>[\w-]+)/versions/$', views.WebappVersionList.as_view(),
        name="webapp_version_list"),
    url(r'^apps/(?P<docker_name>[\w-]+)/versions/(?P<pk>\d+)/update',
        views.WebappVersionUpdate.as_view(), name="webapp_version_update"),
    url(r'^apps/(?P<docker_name>[\w-]+)/json$', views.WebappJson.as_view(), name='webapp_json'),
    url(r'^apps/(?P<docker_name>[\w-]+)$', views.JobCreate.as_view(), name='webapp_detail'),

    url(r'^tags/$', views.TagList.as_view(), name='tag_list'),
    url(r'^tags/(?P<slug>[\w-]+)$', views.TagWebappList.as_view(), name='tag_webapp_list'),

    url(r'^jobs/$', views.JobList.as_view(), name='job_list'),
    url(r'^jobs/(?P<pk>\d+)$', views.JobDetail.as_view(), name='job_detail'),
    url(r'^jobs/(?P<pk>\d+)/abort$', views.JobAbort.as_view(), name='job_abort'),
    url(r'^jobs/(?P<pk>\d+)/delete$', views.JobDelete.as_view(), name='job_delete'),
    url(r'^jobs/(?P<pk>\d+)/archive$', views.JobFileDownloadAll.as_view(), name='job_download_all'),
    url(r'^jobs/(?P<pk>\d+)/download/(?P<filename>(.*))$', views.JobFileDownload.as_view(),
        name='job_download_file'),

    url(r'^profile$', views.UserUpdate.as_view(), name='user_detail'),
    url(r'^profile/token/update$', views.UserToken.as_view(), name='user_token'),
    url(r'^profile/ssh/add$', views.UserSSHAdd.as_view(), name='user_ssh_add'),
    url(r'^profile/ssh/delete$', views.UserSSHDelete.as_view(), name='user_ssh_delete'),
    url(r'^profile/password$', views.UserPasswordUpdate.as_view(), name='user_password'),
    url(r'^profile/need_validation$', views.UserNeedValidation.as_view(),
        name='user_need_validation'),

    url(r'^metrics$', views.Metrics.as_view(), name='metrics'),

    # Terms of service urls
    url(r'^tos$', views.TosDetail.as_view(), name='tos_detail'),

    #  url(r'^runners/$', views.RunnerList.as_view(), name='runner_list'),
    #  url(r'^runners/_add$', views.RunnerCreate.as_view(), name='runner_create'),
    #  url(r'^runners/(?P<pk>\d+)/update$', views.RunnerUpdate.as_view(), name='runner_update'),
    #  url(r'^runners/(?P<pk>\d+)/delete$', views.RunnerDelete.as_view(), name='runner_delete'),

    url(r'^auth$', views.auth, name="auth"),


    # important legacy URLs (from the rails implementation)
    url(r'^webapps/(?P<pk>\d+)/?$',  views.LegacyWebappDetail.as_view()),
    url(r'^app/(?P<slug>[\w-]+)/?$', views.LegacyWebappDetail.as_view()),
]


# error handlers
# NOTE: the 404 and 500 handlers are ignored when settings.DEBUG is enabled
django.conf.urls.handler400 = partial(views.error_handler,
        400, "Bad Request", django.views.defaults.bad_request)
django.conf.urls.handler403 = partial(views.error_handler,
        403, "Forbidden", django.views.defaults.permission_denied)
django.conf.urls.handler404 = partial(views.error_handler,
        404, "Not Found", django.views.defaults.page_not_found)
django.conf.urls.handler500 = partial(views.error_handler,
        500, "Server Error", django.views.defaults.server_error)

django/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views


urlpatterns = [
    # Django admin
    url(settings.ADMIN_URL, admin.site.urls),

    # Allgo stuff here
    url(r'', include('main.urls')),
    url(r'', include('jwt_auth.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^api/v1/', include('api.v1.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        url(r'^400/$',
            default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$',
            default_views.permission_denied,
            kwargs={'exception': Exception('Permission denied!')}),
        url(r'^404/$',
            default_views.page_not_found,
            kwargs={'exception': Exception('Page not found!')}),
        url(r'^500/$', default_views.server_error),
    ]

django/allgo/api/v1/views.py
import logging
import os
from   typing import Mapping, Union

import config.env
from django.core.validators import ValidationError
from django.core.exceptions import PermissionDenied
from django.db import transaction
from django.http import JsonResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import View

import api.v1.metrics as metrics

from main.helpers import (upload_data, get_base_url, lookup_job_file, get_request_user, abort_job,
        delete_job)
from main.mixins import JobAuthMixin
from main.models import Job, Webapp, JobQueue

log = logging.getLogger('allgo')

DATASTORE = config.env.ALLGO_DATASTORE
BUF_SIZE = 65536


def get_link(jobid, filename, request):
    return '/'.join((get_base_url(request), "api/v1/datastore", str(jobid), filename))


class APIJobView(JobAuthMixin, View):
    handle_deleted_job = lambda self: None

    @classmethod
    def as_view(cls, **kw):
        return csrf_exempt(transaction.non_atomic_requests(super().as_view(**kw)))

    def get(self, request, pk):
        try:
            job = Job.objects.get(id=pk)
            files = {}
            for filename in os.listdir(job.data_dir):
                if lookup_job_file(job.id, filename):
                    files[filename] = get_link(job.id, filename, request)

            response = {
                job.id: files,
                "status": "done" if job.result==Job.SUCCESS else job.status.lower(),
            }
            return JsonResponse(response)
        except Job.DoesNotExist as e:
            log.error("Job not found %s", str(e))
            return JsonResponse({'error': 'Job not found'}, status=404)

    def delete(self, request, pk):
        job, status, message = delete_job(int(pk))
        level = "info" if status == 200 else "error"
        return JsonResponse({level: message}, status=status)

class APIJobAbortView(JobAuthMixin, View):

    @classmethod
    def as_view(cls, **kw):
        return csrf_exempt(super().as_view(**kw))

    def post(self, request, pk):
        msg = abort_job(int(pk))
        return JsonResponse({'info': msg})


class Metrics(View):
    """Metrics view provides only a get access."""

    def get(self, request, app_id, what):
        """Method used when accessing the Metrics Api.

            :param request: the request object.
            :param  app_id: the id of the app we want metrics from.
            :type   app_id: integer
            :param    what: the kind of metrics we want.
            :type     what: keyword, key of metrics.ACTIONS
        """
        user = get_request_user(request)
        if not user:
            msg  = "API request without http authorisation\n"
            msg += "\tagent : %s\n\tadress : %s\n\tquery : %s\n"
            log.info(
                msg,
                request.META.get('HTTP_USER_AGENT', 'agent_unknown'),
                request.META.get('REMOTE_ADDR', 'remote_adress_unknown'),
                request.META.get('QUERY_STRING', 'query_unknown'),
            )

            msg = 'API request without http authorisation'
            return JsonResponse({'error': msg}, status=401)

        try:
            msg = "%s is asking for '%s' with app_id '%s'"
            log.info(msg, user, what, app_id)

            if user.is_superuser:
                app = Webapp.objects.get(id=app_id)
            else:
                app = Webapp.objects.get(id=app_id, user=user)
            log.info("app name is *%s*", app.name)

            from_ = request.GET.get('from', None)
            to    = request.GET.get('to',   None)
            step  = request.GET.get('step', None)
            msg = "asked from '%s' to '%s', step of '%s'"
            log.info(msg, from_, to, step)

            # jobs is a dictionnary
            jobs = metrics.ACTIONS[what](app_id, from_, to, step)
            return JsonResponse({ app.name: jobs })

        except Webapp.DoesNotExist as e:
            log.error("Webapp not found -%s-", str(e))
            return JsonResponse({'error': 'Webapp not found'}, status=404)

        except metrics.ParamError as e:
            # the error should have already be logged
            return JsonResponse({'error': str(e)}, status=400)

        except KeyError as e:
            log.error("Metrics action %s is unknown.", str(e) )
            return JsonResponse({'error': str(e)}, status=404)

def get_webapp(post: Mapping[str, str]) -> Union[JsonResponse,Webapp]:
    webapp_id = post.get("job[webapp_id]")
    docker_name = post.get("job[webapp]")

    try:
        if webapp_id is not None:
            if docker_name is not None:
                return JsonResponse(
                        {"error": "must provide either 'job[webapp]' or 'job[webapp_id]', not both"})
            elif webapp_id.isdigit():
                return Webapp.objects.get(id=webapp_id)
            else:
                # The API used to accept an id or docker_name as `job[webapp]`. It was not very clean,
                # but we keep it so as not to break existing code.
                docker_name = webapp_id

        if docker_name is None:
            return JsonResponse({"error": "no app selected (must provide either 'job[webapp]=NAME'"
                    " or 'job[webapp_id]=ID')"}, status=400)
        else:
            return Webapp.objects.get(docker_name=docker_name)

    except Webapp.DoesNotExist:
        return JsonResponse({'error': 'application not found'}, status=404)


@csrf_exempt
def jobs(request):
    user = get_request_user(request)
    if not user:
        log.info("API request without http authorisation %s %s %s", request.META['HTTP_USER_AGENT'],
                 request.META['REMOTE_ADDR'], request.META['QUERY_STRING'])
        return JsonResponse({'error': 'API request without http authorisation'}, status=401)

    if request.method != "POST":
        return JsonResponse({"error": "method not allowed"}, status=405)
    try:
        post = request.POST
    except Exception:
        return JsonResponse({"error": "malformatted request body"}, status=400)

    if isinstance((app := get_webapp(request.POST)), JsonResponse):
        return app

    requested_version = request.POST.get('job[version]')
    if requested_version == "sandbox" and app.sandbox_state == Webapp.RUNNING:
        version = "sandbox"
    elif (wv := app.get_webapp_version(requested_version)) is not None:
        version = wv.number
    else:
        return JsonResponse({"error":
            "This app is not yet published" if requested_version is None else
            f"This app does not have a version named {requested_version!r}"},
            status=404)

    queue = app.job_queue
    if 'job[queue]' in request.POST:
        try:
            queue = JobQueue.objects.get(name=request.POST['job[queue]'])
        except JobQueue.DoesNotExist:
            return JsonResponse({'error': 'Unknown queue'}, status=400)

    log.info("Job submit by user %s", user)
    job = Job(param=request.POST.get('job[param]', ''), queue=queue, webapp=app, user=user)
    job.version = version
    # run the Job validators
    try:
        job.save()
    except ValidationError as e:
        return JsonResponse({'error': "Invalid parameters: %s" % e.message_dict}, status=400)

    # FIXME: possible infoleak: because we have ATOMIC_REQUESTS=True the
    # current id can be reused for another job in case anything fails before
    # the end of the request
    job.files = upload_data(request.FILES.values(), job)

    # start the job
    job.state = Job.WAITING
    job.save()

    path = reverse('api:job', kwargs={'pk':job.id})
    response = {
        "avg_time": 0, # legacy, not relevant anymore
        "id"      : job.id,
        "url"     : get_base_url(request)+path,
    }

    return JsonResponse(response)


class APIDownloadView(JobAuthMixin, View):

    def get(self, request, *args, **kwargs):
        log.error("datastore requests must be served by nginx (bad config!)")
        return JsonResponse({'error': 'Internal Server Error'}, status=500)

django/allgo/templates/partials/_footer.html
{% load static env_var %}

<footer class="footer container-fluid w-100 bg-dark text-light py-3">
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <h5>A<span class="allgo-pipes">||</span>Go</h5>
        <p class="copyright">&copy; {% now "Y" %}</p>
      </div>
      <div class="col-sm-3">
        <h5>Get started</h5>

        <ul>
          <li><a href="{% url 'main:home' %}">Home</a></li>
          <li><a href="{% url 'account_signup' %}">Sign up</a></li>
          <li><a href="{% url 'main:webapp_list' %}">Explore</a></li>
        </ul>
      </div>

      <div class="col-sm-3">
        <h5>About us</h5>

        <ul>
          <li><a href="https://wiki.inria.fr/sed_ren/">/SED/</a></li>
          <li><a href="{% url 'main:tos_detail' %}">Terms</a></li>
          {% comment Will be reintegrated with the RGPD %}
          <li><a href="#">Privacy</a></li>
          {% endcomment %}
        </ul>
      </div>

      <div class="col-sm-3">
        <h5>Support</h5>

        <ul>
          <li><a href="https://allgo.gitlabpages.inria.fr/doc/">Documentation</a></li>
          <li><a href="{% env_var "ALLGO_HELPDESK_URL" %}">Helpdesk</a></li>
          <li><a href="{% env_var "ALLGO_BUG_TRACKER_URL" %}">Report an issue</a></li>
          <li><a href="{% env_var "ALLGO_CONTACT" %}">Contact</a></li>
        </ul>
      </div>
    </div>
    <div class="logos">
    <a href="https://inria.fr"><img class="float-left" src="{% static 'images/inria.png' %}"></a>
    <a href="https://www.irisa.fr"><img class="float-right" src="{% static 'images/irisa.png' %}"></a>
    </div>
  </div>
</footer>

django/allgo/templates/partials/_form_account_messages.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <div class="container">{{ error|escape }}</div>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    {% endfor %}
  {% endfor %}

  {% for error in form.non_field_errors %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <div class="container">{{ error|escape }}</div>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  {% endfor %}
{% endif %}

django/allgo/templates/partials/_form_messages.html
{% for field in form %}
  {% for error in field.errors %}
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <div class="container">{{ error|escape }}</div>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% endfor %}
{% endfor %}

django/allgo/templates/partials/_header.html
{% load static activelink socialaccount%}

<header class="container-fluid">
  <div class="container">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand text-hide" href="{% url 'main:home' %}">
        <img src="{% static "images/logo-allgo.png" %}" width="50px" height="50px" alt="allgo logo">A||go</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li 
            class="nav-item {% is_active request 'webapp_list' 'webapp_detail' %}">
            <a class="nav-link" href="{% url 'main:webapp_list' %}"><i class="fas fa-search"></i> Browse</a>
          </li>
          <li {# TODO: put active link if possible #}>
            <a class="nav-link" href="https://allgo.gitlabpages.inria.fr/doc/"><i class="fas fa-book"></i> Documentation</a>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">
          {% if sign_in_url %}
          <a href="{{ sign_in_url }}" class="btn btn-primary">Log in{% if sign_in_provider %} with {{sign_in_provider}}{% endif %}</a>
          {% endif %}
          {% if user.is_authenticated %}
          <li class="nav-item {% is_active request 'user_webapp_list' 'webapp_update' 'webapp_creation' 'webapp_sandbox_panel' %}">
            <a class="nav-link" href="{% url 'main:user_webapp_list' user.get_username %}"><i class="fas fa-cloud"></i> Apps</a>
          </li>
          <li  class="nav-item {% is_active request 'job_list' 'job_detail' 'webapp_detail' 'job_delete' %}">
            <a class="nav-link" href="{% url 'main:job_list' %}"><i class="fas fa-database"></i> Jobs</a>
          </li>
          {% comment %}
          <li  class="nav-item {% is_active request 'runner_list' 'runner_create' 'runner_update' 'runner_delete' %}">
            <a class="nav-link" href="{% url 'main:runner_list' %}"><i class="fab fa-hubspot"></i> Runners</a>
          </li>
          {% endcomment %}
          <li  class="nav-item {% is_active request 'metrics' %}">
            <a class="nav-link" href="{% url 'main:metrics' %}"><i class="fas fa-chart-bar"></i> Metrics</a>
          </li>
          <li class="nav-item {% is_active request 'user_detail' 'user_token' 'user_ssh_add' 'user_ssh_delete' 'user_password' %}">
            <a class="nav-link" href="{% url 'main:user_detail' %}"><i class="fas fa-user"></i> Profile</a>
          </li>
          <li class="nav-item {% is_active request 'account_logout' %}">
            <form style="display: inline" method="post" action="{% url 'account_logout' %}?next={{ view.request.get_full_path | urlencode }}">
              {% csrf_token %}
              <button type="submit" class="btn btn-primary"><i class="fas fa-sign-out-alt"></i> Sign out</a></button>
            </form>
          </li>
          {% endif %}
        </ul>

      </div>
    </nav>
  </div>
</header>

django/allgo/templates/partials/_messages.html
{% for message in messages %}
<div class="container-fluid alert-{{ message.tags }} alert alert-container">
  <div class="container">
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
      <div class="container">{{ message }}</div>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
</div>
{% endfor %}

django/allgo/templates/partials/_pagination.html
{% if is_paginated %}
<nav aria-label="Webapp page navigation">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1">Previous</a>
    </li>
    {% endif %}
    {% for page in page_obj.paginator.page_range %}
      {% if page == page_obj.number %}
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1">{{ page }}</a>
        </li>
      {% else %}
        <li class="page_item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
      </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1">Next</a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

django/allgo/templates/partials/_webapp_list.html
{% load static converters humanize %}
<div class="row">
{% for webapp in webapps %}

  <div class="col">
    <div class="card card-webapp" style="width: 18rem;">
      <div class="card-header">
        {% if webapp.logo_file_name %}
        <img class="card-img-top img-thumbnail rounded-circle mx-auto d-block" src="{% get_media_prefix %}{{ webapp.docker_name }}/{{ webapp.logo_file_name }}" alt="{{ webapp.title }} logo">
        {% else %}
        <img class="card-img-top img-thumbnail rounded-circle mx-auto d-block" src="{% static 'images/webapp-default-logo.svg' %}" alt="{{ webapp.title }} logo" style="opacity: 0.5;">
        {% endif %}
        <h5 class="card-title text-center"><a href="{% url 'main:webapp_detail' webapp.docker_name %}">{{ webapp.name | fancy_webapp_name }}</a></h5>
        <h6 class="card-subtitle text-muted text-center">{{ webapp.contact | email2name }} - Updated {{ webapp.updated_at | naturalday }}</h6>
      </div>
      <div class="card-body">
        <nav class="navbar">
          <ul class="nav nav-bar mx-auto">
            <li class="nav-item">
              <a 
                class="nav-link"
                href="{% url 'main:webapp_detail' webapp.docker_name %}"
                title="Start a job"
                data-toggle="tooltip"
                data-placement="bottom" ><i class="fas fa-play" data-fa-transform="shrink-10 up-.5" data-fa-mask="fas fa-circle"></i><span class="text-hide">Run a job</a></li>
            {% if webapp.notebook_gitrepo %}
            <li class="nav-item">
              <a
                class="nav-link"
                href="/jupyter?repo={{ webapp.notebook_gitrepo }}"
                title="Start a Jupyter notebook"
                data-toggle="tooltip"
                data-placement="bottom"><i class="fas fa-sticky-note" data-fa-transform="shrink-10 up-.5" data-fa-mask="fas fa-circle"></i><span class="text-hide">Run notebook</a></li>
	    {% endif %}
            {% if webapp.user == user and webapp.sandbox_state != webapp.IDLE %}
            <li class="nav-item">
              <a
                class="nav-link app-unfinished"
                href="{% url 'main:webapp_sandbox_panel' webapp.docker_name %}"
                title="There is an active sandbox"
                data-toggle="tooltip"
                data-placement="bottom"><i class="fas fa-exclamation-circle"></i><span class="text-hide">There is an active sandbox</span></a></li>
            {% endif %}
          </ul>
        </nav>
        <p class="card-text">
        {% if webapp.description %}
        {{ webapp.description|truncatechars:200 }}
        {% else %}
        No description available for this application.
        {% endif %}
        </p>
      </div>
      <div class="card-footer text-muted">
        <div class="row">
          <div class="col-1">
            <i class="fas fa-tags"></i>
          </div>
          <div class="col">
            <ul class="list-inline app-tags small">
              {% for tag in webapp.tags.all %}
              <li class="list-inline-item"><a class="badge badge-secondary" href="{% url 'main:tag_webapp_list' tag.slug %}">{{ tag.name }}</a></li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endfor %}
</div>